import { ArrowRight, BadgeCheck, BookOpen, CalendarCheck2, FileLock2, HeartHandshake, ShieldCheck, UserCheck } from 'lucide-react';
import { Link, useLocation } from 'react-router-dom';
import { AppLayout } from '../components/Layout';

export function HowItWorksPage() {
  return <AppLayout><section className="info-hero"><div className="container"><span className="kicker">How IlmSaathi works</span><h1>Your next lesson—without the uncertainty.</h1><p>Choose thoughtfully, request privately, and always know what happens next.</p></div></section><section className="section"><div className="container info-steps"><div><span>01</span><BookOpen /><h2>Discover</h2><p>Browse only approved educators. Filter by subject, language, availability and price without creating an account first.</p></div><div><span>02</span><UserCheck /><h2>Choose</h2><p>See teaching style, learner feedback and precise verification labels—not one misleading badge.</p></div><div><span>03</span><CalendarCheck2 /><h2>Request</h2><p>Ask for a time. Your educator confirms before a secure payment link or meeting link is released.</p></div><div><span>04</span><HeartHandshake /><h2>Grow</h2><p>Learn live, leave a review after completion and repeat only when the fit feels right.</p></div></div><div className="container info-cta"><h2>Start with one meaningful class.</h2><Link className="button button--large" to="/explore">Explore educators <ArrowRight /></Link></div></section></AppLayout>;
}

export function SafetyPage() {
  return <AppLayout><section className="safety-hero"><div className="container"><ShieldCheck /><span className="kicker kicker--light">Trust is a product feature</span><h1>Safe enough to ask. Clear enough to trust.</h1><p>We collect less, explain more and keep authority on the server—not in a hidden menu.</p></div></section><section className="section"><div className="container safety-grid"><article><BadgeCheck /><h2>Verification with honest labels</h2><p>Contact, identity, qualifications, self-declared experience and subject approval are separate facts.</p></article><article><FileLock2 /><h2>Private evidence stays private</h2><p>Randomised storage paths, short-lived reviewer access and an audit record for every privileged view.</p></article><article><HeartHandshake /><h2>Respectful learning boundaries</h2><p>No class recording by default, no public contact exchange and no unrestricted chat in the pilot.</p></article><article><ShieldCheck /><h2>Real accountability</h2><p>Block and report controls, traceable moderation states and no silent educator approval.</p></article></div></section></AppLayout>;
}

export function LegalPage() {
  const { pathname } = useLocation(); const privacy = pathname.includes('privacy');
  return <AppLayout><article className="legal-page container"><span className="kicker">Pilot document · version 0.1</span><h1>{privacy ? 'Privacy notice' : 'Terms of use'}</h1><p className="legal-lead">This page is a product-ready structure, not final legal advice. Replace it with counsel-reviewed India launch text before inviting real users.</p><h2>{privacy ? 'What we collect' : 'Who may use IlmSaathi'}</h2><p>{privacy ? 'We collect the minimum account, learning preference, educator application and class information needed to operate the service. For an under-18 learner, the production service will also keep the parent or guardian consent record required to protect the child account. Private evidence is not used for advertising or product analytics.' : 'Learning has no age limit. Educators must be 18 or older and are subject to review and subject-by-subject approval. Under-18 learner accounts will be enabled publicly only after verified parent or guardian consent and child-specific privacy and safeguarding controls are complete.'}</p><h2>{privacy ? 'Why we use it' : 'Learning and teaching expectations'}</h2><p>{privacy ? 'To create your account, match your chosen filters, administer educator review, support classes, prevent abuse and meet legal obligations.' : 'Users must communicate respectfully, provide accurate application information and not share protected meeting links or private evidence.'}</p><h2>Your choices</h2><p>You may ask to correct your profile, request account deletion or contact support about a privacy or safety concern. Some payment, audit or safety records may need a defined retention period.</p><h2>Contact</h2><p>Configure a real grievance/support contact before launch. Current development placeholder: support@ilmsaathi.example.</p></article></AppLayout>;
}

export function NotFoundPage() {
  return <AppLayout><div className="not-found container"><span>404</span><h1>This path hasn’t been mapped yet.</h1><p>Let’s bring you back to a place where learning can begin.</p><Link className="button button--large" to="/">Return home</Link></div></AppLayout>;
}
